services:
  pipeline:
    build:
      context: .
    container_name: data_pipeline
    ports:
      - "4040:4040"  # UI port
    environment:
      - SPARK_DRIVER_MEMORY=${SPARK_DRIVER_MEMORY}
      - SPARK_EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY}
      - SPARK_EXECUTOR_CORES=${SPARK_EXECUTOR_CORES}
    volumes:
      - ./data:/opt/spark/app/data
      - ./src:/opt/spark/app/src
      - ./logs:/opt/spark/app/logs