spark:
  app_name: "trab-final-rel-pedidos"
  driver_memory: "2G"
  driver_cores: "2"
  executor_instances: "2"
  executor_memory: "2G"
  executor_cores: "2"
  default_parallelism: "4"

# Aqui definimos caminhos relativos à raiz do projeto
paths:
  pagamentos: "data/input/dataset-json-pagamentos/data/pagamentos/"
  pedidos: "data/input/datasets-csv-pedidos/data/pedidos/"
  output: "data/output/pedidos_legit_recusados/"

# Configurações de Processamento
file_options:
  pagamentos_json:
    compression: "gzip"
  pedidos_csv:
    compression: "gzip"
    header: True
    sep: ";"
    